<?php

namespace Database\Seeders;

use App\Models\pembuatan_stnk;
use Illuminate\Database\Seeder;

class StnkTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        pembuatan_stnk::create([
            'no_regis' => '1000',
            'no_stnk' => NULL,
            'merk' => 'Honda',
            'type' => 'D1231243242 S/Y',
            'jenis' => 'Sepeda Motor',
            'model' => 'Sepeda Motor',
            'thn_pembuatan' => 2015,
            'silinder' => '150 CC',
            'nmr_rangka' => 'MHJASHD28734923423DWE',
            'nmr_mesin' => 'KM3232423',
            'warna_kendaraan' => 'Hitam',
            'bahan_bakar' => 'Bensin',
            'warna_tnkb' => 'Hitam',
            'thn_registrasi' => 2015,
            'nmr_urut' => 123,
            'nmr_faktur' => 12412,
            'apm' => 'sfsadf',
            'nmr_pib' => 123412,
            'nmr_sut' => 1234124,
            'nmr_tanda_pendaftaran' => 123143,
            'kepemilikan' => 'asdfsadf',
            'nama_pemilik' => 'Naufal',
            'alamat_pemilik' => 'Bks',
            'kode_pos' => 31342,
            'nmr_telepon' => '081919231231',
            'nmr_ktp' => '23412731234234',
            'kitas' => 'dshasdfas',
            'baru' => 'baru beli',
            'perubahan' => 'warna oli',
            'persyaratan_khusus' => 'dfksdfs',
            'masa_berlaku' => NULL,
            'pajak_berlaku' => NULL,
            'file' => 'ckjsdnckjdsc.pdf',
            'status' => 'PROSES',
            'user_id' => 3
        ]);

        // pembuatan_stnk::create([
        //     'no_regis' => '1001',
        //     'no_stnk' => NULL,
        //     'merk' => 'Honda',
        //     'type' => '4213ASDAS S/Y',
        //     'jenis' => 'Sepeda Motor',
        //     'model' => 'Sepeda Motor',
        //     'thn_pembuatan' => 2016,
        //     'silinder' => '156 CC',
        //     'nmr_rangka' => 'MsHJASHD28734923423DWE',
        //     'nmr_mesin' => 'KM323er2423',
        //     'warna_kendaraan' => 'Hitam',
        //     'bahan_bakar' => 'Bensin',
        //     'warna_tnkb' => 'Hitam',
        //     'thn_registrasi' => 2016,
        //     'nmr_urut' => 123,
        //     'nmr_faktur' => 12412,
        //     'apm' => 'sfsadf',
        //     'nmr_pib' => 45345,
        //     'nmr_sut' => 1234124,
        //     'nmr_tanda_pendaftaran' => 123453143,
        //     'kepemilikan' => 'asdfsadf',
        //     'nama_pemilik' => 'Gasot',
        //     'alamat_pemilik' => 'Bks',
        //     'kode_pos' => 31342,
        //     'nmr_telepon' => '0123',
        //     'nmr_ktp' => '25345346',
        //     'kitas' => 'dshasdfas',
        //     'baru' => 'baru beli',
        //     'perubahan' => 'warna oli',
        //     'persyaratan_khusus' => 'dfksdfs',
        //     'masa_berlaku' => NULL,
        //     'pajak_berlaku' => NULL,
        //     'file' => 'ckjsdnckjdsc.pdf',
        //     'status' => 'PROSES',
        //     'user_id' => 3
        // ]);

        // pembuatan_stnk::create([
        //     'no_regis' => '1002',
        //     'no_stnk' => NULL,
        //     'merk' => 'Honda',
        //     'type' => '4213ASDASDAS S/Y',
        //     'jenis' => 'Sepeda Motor',
        //     'model' => 'Sepeda Motor',
        //     'thn_pembuatan' => 2017,
        //     'silinder' => '156 CC',
        //     'nmr_rangka' => 'MsHJASHD28734923423DWE',
        //     'nmr_mesin' => 'KM323er2423',
        //     'warna_kendaraan' => 'Hitam',
        //     'bahan_bakar' => 'Bensin',
        //     'warna_tnkb' => 'Hitam',
        //     'thn_registrasi' => 2017,
        //     'nmr_urut' => 123,
        //     'nmr_faktur' => 12412,
        //     'apm' => 'sfsadf',
        //     'nmr_pib' => 45345,
        //     'nmr_sut' => 1234124,
        //     'nmr_tanda_pendaftaran' => 123453143,
        //     'kepemilikan' => 'asdfsadf',
        //     'nama_pemilik' => 'Nisa',
        //     'alamat_pemilik' => 'Bks',
        //     'kode_pos' => 31342,
        //     'nmr_telepon' => '123',
        //     'nmr_ktp' => '25345346',
        //     'kitas' => 'dshasdfas',
        //     'baru' => 'baru beli',
        //     'perubahan' => 'warna oli',
        //     'persyaratan_khusus' => 'dfksdfs',
        //     'masa_berlaku' => NULL,
        //     'pajak_berlaku' => NULL,
        //     'file' => 'ckjsdnckjdsc.pdf',
        //     'status' => 'PROSES',
        //     'user_id' => 4
        // ]);

        // pembuatan_stnk::create([
        //     'no_regis' => '1003',
        //     'no_stnk' => NULL,
        //     'merk' => 'Honda',
        //     'type' => '4213ASDAS S/Y',
        //     'jenis' => 'Mini Bus',
        //     'model' => 'Msfsdf',
        //     'thn_pembuatan' => 2016,
        //     'silinder' => '156 CC',
        //     'nmr_rangka' => 'MsHJASHD28734923423DWE',
        //     'nmr_mesin' => 'KM323er2423',
        //     'warna_kendaraan' => 'Hitam',
        //     'bahan_bakar' => 'Bensin',
        //     'warna_tnkb' => 'Hitam',
        //     'thn_registrasi' => 2016,
        //     'nmr_urut' => 123,
        //     'nmr_faktur' => 12412,
        //     'apm' => 'sfsadf',
        //     'nmr_pib' => 45345,
        //     'nmr_sut' => 1234124,
        //     'nmr_tanda_pendaftaran' => 123453143,
        //     'kepemilikan' => 'asdfsadf',
        //     'nama_pemilik' => 'danil',
        //     'alamat_pemilik' => 'Bks',
        //     'kode_pos' => 31342,
        //     'nmr_telepon' => '1231',
        //     'nmr_ktp' => '25345346',
        //     'kitas' => 'dshasdfas',
        //     'baru' => 'baru beli',
        //     'perubahan' => 'warna oli',
        //     'persyaratan_khusus' => 'dfksdfs',
        //     'masa_berlaku' => NULL,
        //     'pajak_berlaku' => NULL,
        //     'file' => 'ckjsdnckjdsc.pdf',
        //     'status' => 'PROSES',
        //     'user_id' => 4
        // ]);

        // pembuatan_stnk::create([
        //     'no_regis' => '1004',
        //     'no_stnk' => NULL,
        //     'merk' => 'Honda',
        //     'type' => '4213ASDAS S/Y',
        //     'jenis' => 'Mini Bus',
        //     'model' => 'Msfsdf',
        //     'thn_pembuatan' => 2016,
        //     'silinder' => '156 CC',
        //     'nmr_rangka' => 'MsHJASHD28734923423DWE',
        //     'nmr_mesin' => 'KM323er2423',
        //     'warna_kendaraan' => 'Hitam',
        //     'bahan_bakar' => 'Bensin',
        //     'warna_tnkb' => 'Hitam',
        //     'thn_registrasi' => 2016,
        //     'nmr_urut' => 123,
        //     'nmr_faktur' => 12412,
        //     'apm' => 'sfsadf',
        //     'nmr_pib' => 45345,
        //     'nmr_sut' => 1234124,
        //     'nmr_tanda_pendaftaran' => 123453143,
        //     'kepemilikan' => 'asdfsadf',
        //     'nama_pemilik' => 'qwewqe',
        //     'alamat_pemilik' => 'ads',
        //     'kode_pos' => 31342,
        //     'nmr_telepon' => '1231',
        //     'nmr_ktp' => '25345346',
        //     'kitas' => 'dshasdfas',
        //     'baru' => 'baru beli',
        //     'perubahan' => 'warna oli',
        //     'persyaratan_khusus' => 'dfksdfs',
        //     'masa_berlaku' => NULL,
        //     'pajak_berlaku' => NULL,
        //     'file' => 'ckjsdnckjdsc.pdf',
        //     'status' => 'PROSES',
        //     'user_id' => 4
        // ]);
    }
}
